### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by ZhibinPeng** [kkaiwwana/MVPbev#1]
Can you relink the dataset? There is a problem with unzipping after downloading.

**Comment by kkaiwwana** [comment]
Could you explain more clearly what issue with unzipping is?

**Comment by ZhibinPeng** [comment]
“gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now”
And i made sure the download was complete

**Comment by kkaiwwana** [comment]
My fault. I checked data in remote of which file size is 13.7G, I guess that's same as what you downloaded. It oughts to be ~14.7G.

I'll re-upload that in these days and update the link. Thank you for your issue. I'll let you knew when I have that done.

**Comment by ZhibinPeng** [comment]
Hahaha thank you.

**Comment by kkaiwwana** [comment]
That should be fine now. Feel free to reopen this issue if you meet other problem.
