### ISSUE TITLE
Are there plans to expand MVPBEV to video generation?

### ISSUE THREAD

**Issue by KevenLee** [kkaiwwana/MVPbev#2]
Are there plans to expand MVPBEV to video generation?

**Comment by kkaiwwana** [comment]
Thank you for your proposal, but, no, it requires massive work (basically to ensure temporal consistency is another big problem) which is not in our plan. 

For video generation, you can check up MagicDrive which is brilliant and close to our work and they have their implementation  for video generation  in [this](https://github.com/cure-lab/MagicDrive/tree/video) branch.

Closing this issue. Feel free to re-open it for other concerns.
